name: "Checks"
on:
  - pull_request

jobs:
  build:
    name: "Build FNS actor"
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Install node
        uses: actions/setup-node@v2
        with:
          node-version: '16.13.0'
      - name: Install latest stable
        uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Install yarn
        run: npm install -g yarn
      - name: Set npmrc
        run: |
          yarn config set @zondax:registry https://verdaccio.zondax.net/
          npm config set //verdaccio.zondax.net/:_authToken "$VERDACCIO_TOKEN"
          npm config set //verdaccio.zondax.net/:always-auth true
        env:
          VERDACCIO_TOKEN: ${{ secrets.VERDACCIO_READ_TOKEN }}
      - name: Install deps
        run: make deps
      - name: Build WASM file
        run: make build
      - name: Cache/restore binaries
        uses: actions/cache@v1
        with:
          path: ./fil-fns-actor.wasm
          key: ${{ runner.os }}-${{ github.run_id }}
      - uses: actions/upload-artifact@v3
        with:
          name: fil-fns-actor-previous.wasm
          path: ./fil-fns-actor.wasm

  diff:
    name: "Check diff"
    needs: ["build"]
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Cache/restore binaries
        uses: actions/cache@v1
        with:
          path: ./build
          key: ${{ runner.os }}-${{ github.run_id }}
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          github_token: ${{secrets.GITHUB_TOKEN}}
          workflow: main.yaml
          pr: ${{github.event.pull_request.number}}
          event: push
          name: fil-fns-actor-previous.wasm
      - name: Display structure of downloaded files
        run: ls -l